spring:
  profiles:
    active: prod

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: anywhere@123
    idle-timeout: 60000
    maximum-pool-size: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
    max-lifetime: 1765060  #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
    pool-name: alarm-pool

mybatis:
  mapperLocations: classpath:mapper/*.xml

